version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: >
      sh -c "python manage.py makemigrations && \
             python manage.py migrate && \
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    env_file:
      - ./.env.dev
  db:
    image: postgres
    env_file:
      - ./.env.dev
    volumes:
      - drf_news_postgres_data:/var/lib/postgresql/data/

volumes:
  drf_news_postgres_data: